target_ip:  # 目标域名/ip
  'baidu.com'
count:      # 测试次数
  10
protocol:   # 协议，目前只支持icmp，勿动
  - 'icmp'
cell:       # 测试间隔，单位秒
  1
row_num:    # 保留最近n行记录
  5
string_length:  # 行长度，避免出现脏字符，出现脏字符就加长
  100
show_pic:   # 是否展示折线图，1代表展示，0代表不展示
  0
pic_dir:    # 生成折线图保存的文件夹
  './output'
datail_graph:   # 是否开启精确刻度，开启可使时间刻度不重叠，关闭可显著缩小图片宽度，低于1600条每条刻度都显示，超过1600条刻度会合并处理
  0
range:      # 简单的判断，满足此条件则记录至画布，因为超时会置为-1，所以-1的情况也要考虑
  'i != 0'
unattended: # 是否为无人值守，有人值守时，按回车键可强制停止测速且生成图片后且点击任意键退出，无人值守不可中途停止，且结束自动退出
  1
